* 1
** 熊木杏里 - 風の記憶 / Kaze no Kioku - Anri Kumaki (Bài hát tiếng nhật "ký ức của gió")
   https://www.youtube.com/watch?v=2EibV1kMLSQ
** Enya - Only Time (Official Music Video)
   https://www.youtube.com/watch?v=7wfYIMyS_dI
** When Stars and Salt collide - Coldplay, A Sky Full of Stars (piano/cello cover)- The Piano Guys
   https://www.youtube.com/watch?v=qrHFg47Mopk
** Moby - Everloving
   https://www.youtube.com/watch?v=atyvdC15HFA
** We Found Love - Lindsey Stirling (VenTribe)
   https://www.youtube.com/watch?v=0g9poWKKpbU
** Hallelujah on a Harp - Leonard Cohen Tribute
   https://www.youtube.com/watch?v=WEK4hw7hMgI
* 2
** Snow Patrol - Chasing Cars
   https://www.youtube.com/watch?v=GemKqzILV4w
** 【LIVE】Kana Hanazawa - flattery?
   https://www.youtube.com/watch?v=zA5nCExGRxo
** Jason Mraz - I'm Yours [Official Video]
   https://www.youtube.com/watch?v=EkHTsc9PU2A
** Ed Sheeran - The A Team [Official Video]
   https://www.youtube.com/watch?v=UAWcs5H-qgQ
** Moby - Porcelain
   https://www.youtube.com/watch?v=FAYHTES4whs
** Owl City - Fireflies
   https://www.youtube.com/watch?v=psuRGfAaju4
** 周杰倫 - 稻香 KTV Hương Lúa
   https://www.youtube.com/watch?v=cGJyOxLTebg
** Coldplay - Up&Up (Official Video)
   https://www.youtube.com/watch?v=BPNTC7uZYrI
** [Vietsub | Hán Việt] Tiêu Dao Tuyệt Nhất - Trương Tây (Ost Như Ý Cát Tường 2003)
   https://www.youtube.com/watch?v=3-4sE1GN8ss
* 3
** Holly Henry - Seven Nation Army (TEEMID Cover) ~Faker không giấu nổi vẻ tự hào khi hoàn thành công trình này~
   https://www.youtube.com/watch?v=hTb6ClME6Eg
** Natural Blues. Moby.
   https://www.youtube.com/watch?v=JNWhOJSzZ0M
** Bag Raiders - Shooting Stars
   https://www.youtube.com/watch?v=feA64wXhbjo
** [MV][Kill Me, Heal Me OST] Auditory Hallucination 환청 (ENG+Rom+Han.SUB.) Jang Jae In
   https://www.youtube.com/watch?v=Gg0P9yd0noE
** [Vietsub] The Day You Went Away - M2M.mkv
   https://www.youtube.com/watch?v=L66bOF3dUYs
** Coldplay - Ink (Official Fans' Cut)
   https://www.youtube.com/watch?v=gKM15TaKLUI
* 4
** Jason Mraz & Colbie Caillat - Lucky [Official Video]
   https://www.youtube.com/watch?v=acvIVA9-FMQ
** Of Monsters And Men - Dirty Paws (Official Lyric Video)
   https://www.youtube.com/watch?v=mCHUw7ACS8o
** Of Monsters And Men - Little Talks (Official Video)
   https://www.youtube.com/watch?v=ghb6eDopW8I
** [MV] 케이윌(K.will) - 이러지마 제발 (Please don't...)
   https://www.youtube.com/watch?v=PdUiCJnRptk
** Adele - When We Were Young (Live at The Church Studios)
   https://www.youtube.com/watch?v=DDWKuo3gXMQ
** Coldplay - All I Can Think About Is You (Official Lyric Video)
   https://www.youtube.com/watch?v=KnLNG0WnGsI
* 5
** Stoto - Still Can't Sleep (Original Mix)
   https://www.youtube.com/watch?v=UAHaxlCe29E
** Vitas - Opera N2
   https://www.youtube.com/watch?v=tITWIcNeTjw
** Of Monsters and Men - King And Lionheart (Official Video)
   https://www.youtube.com/watch?v=A76a_LNIYwE
** [Vietsub | Hán Việt] Đồng Thoại - Quang Lương (Music Gift For You No.2)
   https://www.youtube.com/watch?v=DjOEbfGyANA
** Sứ thanh hoa 青花瓷 - Jay Chou
   https://www.youtube.com/watch?v=CZ78y__MIzM
** [Vietsub][HD] Endless Love (The Myth Theme Song) - Jackie Chan & Kim Hee Sun
   https://www.youtube.com/watch?v=EwuyNZDojg8
* 6
** Mirrors - Justin Timberlake
*** (Boyce Avenue feat. Fifth Harmony cover) on Apple & Spotify
    https://www.youtube.com/watch?v=fvEZUbzqqyM
*** Justin Timberlake - Mirrors
    https://www.youtube.com/watch?v=uuZE_IRwLNI
** Vietsub | Hán Việt] Song Phi - Hà Nhuận Đông (Ost Lương Sơn Bá Chúc Anh Đài 2007)
   https://www.youtube.com/watch?v=Vaclu3ZmHlQ
** [MV Full HD] Those Years - Hu Xia [Vietsub + Kara FX] (You Are the Apple of My Eye's OST)
   https://www.youtube.com/watch?v=UBehxEC8c-4
** Of Monsters And Men - Love Love Love (Official Lyric Video)
   https://www.youtube.com/watch?v=beiPP_MGz6I
** Gotye - Somebody That I Used To Know (feat. Kimbra) - official video
   https://www.youtube.com/watch?v=8UVNT4wvIGY
** B.o.B - Airplanes ft. Hayley Williams
   https://www.youtube.com/watch?v=eVcvBmFF_lU
* 7
** [Vietsub+Kara] 5cm/s AMV - Sakura anata ni deaete yokatta
   https://www.youtube.com/watch?v=WAT-Gy6QsTY
** Adele - Set Fire To The Rain (Live at The Royal Albert Hall)
   https://www.youtube.com/watch?v=Ri7-vnrJD3k
** Adele - Rolling in the Deep
   https://www.youtube.com/watch?v=rYEDA3JcQqw
** [Vietsub | Hán Việt] Kiếm Hồn - Lý Vĩ (Ost Tân Anh Hùng Xạ Điêu 2017)
   https://www.youtube.com/watch?v=4MOsX9sE1VA
** Descendants Of The Sun-[HD] OST||Once Again- Kim Na-Young ft Mad Clown
   https://www.youtube.com/watch?v=PKIU4ebQxOA
** TAEYANG - 눈,코,입 (EYES, NOSE, LIPS) M/V
   https://www.youtube.com/watch?v=UwuAPyOImoI
* 8
** Snow Patrol - The Lightning Strike (What If This Storm Ends?)
   https://www.youtube.com/watch?v=S0BDS0-ZwOw
** will.i.am - #thatPOWER ft. Justin Bieber
   https://www.youtube.com/watch?v=DGIgXP9SvB8
** Austin Mahone - Mmm Yeah ft. Pitbull
   https://www.youtube.com/watch?v=MMAppa1cAVo
** CloZee - Secret Place
   https://www.youtube.com/watch?v=soLrXM0EQ8c
** Bệnh Của Anh - Khói [Lyric Video]
   https://www.youtube.com/watch?v=FFwasFKSjSg
** Call Me - Koo [Lyric Video] ( Prod. Danny EB )
   https://www.youtube.com/watch?v=FWkW-YkzCJ4
** [Full MV] 2PM & SNSD - Caribbean Bay CABI Song
   https://www.youtube.com/watch?v=EiheWWaWApc
** DARA - KISS M/V
   https://www.youtube.com/watch?v=ZAqiMCp9zrI
** Imagine Dragons - Whatever It Takes
   https://www.youtube.com/watch?v=gOsM-DYAEhY
** Maroon 5 - Wait
   https://www.youtube.com/watch?v=4uTNVumfm84
** G-DRAGON - HEARTBREAKER M/V
   https://www.youtube.com/watch?v=LOXEVd-Z7NE
** BIGBANG - LIES(거짓말) M/V
   https://www.youtube.com/watch?v=2Cv3phvP8Ro
** GD X TAEYANG - GOOD BOY M/V
   https://www.youtube.com/watch?v=1ZRb1we80kM
** Justin Timberlake - Suit & Tie (Official) ft. JAY Z
   https://www.youtube.com/watch?v=IsUsVbTj2AY
** Moby - Lift Me Up
   https://www.youtube.com/watch?v=CWGNA3u4-Sg
* 9
** Skrillex & Damian "Jr. Gong" Marley - Make It Bun Dem [OFFICIAL VIDEO]
https://www.youtube.com/watch?v=BGpzGu9Yp6Y
** CAZZETTE - She Wants Me Dead (CAZZETTE vs. AronChupa) [Official Video] ft. The High
   https://www.youtube.com/watch?v=FHccClTAdzc
** twenty one pilots: Stressed Out [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=pXRviuL6vMY
** Nelly - Just A Dream
   https://www.youtube.com/watch?v=N6O2ncUKvlg
** Eminem - Rap God (Explicit)
   https://www.youtube.com/watch?v=XbGs_qK2PQA
** Logan | Way Down We Go | Music Video
   https://www.youtube.com/watch?v=LCkyW7RE6Wk
** Cùng Anh - Ngọc Dolil (VRT Mix)
   https://www.youtube.com/watch?v=V9S5QPbzPoo
** Caravan Palace - Lone Digger
   https://www.youtube.com/watch?v=UbQgXeY_zi4
* 10
** Dimitri Vegas, Martin Garrix, Like Mike - Tremor (Official Music Video)
   https://www.youtube.com/watch?v=9vMh9f41pqE
** Requiem For A Dream Full Song HD
   https://www.youtube.com/watch?v=yVIRcnlRKF8
** CAZZETTE - She Wants Me Dead (CAZZETTE vs. AronChupa) [Official Video] ft. The High
   https://www.youtube.com/watch?v=FHccClTAdzc
** The XX - Intro HQ
   https://www.youtube.com/watch?v=AZ1pHmWhIuY
** clubbed to death - Matrix soundtrack
   https://www.youtube.com/watch?v=XbxZargtXug
** In The End (Official Video) - Linkin Park
   https://www.youtube.com/watch?v=eVTXPUF4Oz4
** Numb (Official Video) - Linkin Park
   https://www.youtube.com/watch?v=kXYiU_JCYtU
** Skrillex & Damian "Jr. Gong" Marley - Make It Bun Dem [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=BGpzGu9Yp6Y
** Avicii - Levels
   https://www.youtube.com/watch?v=_ovdm2yX4MA
