* 1
** 川嶋あい / 旅立ちの日に・・・（Lyrics）
https://www.youtube.com/watch?v=DlO308doIyU
** 熊木杏里 - 「桜」（コブクロ 「桜」 のカバー）
   https://www.youtube.com/watch?v=NAnBxv8hJU0
** Hollow Coves - The Woods (Rami & Mitchell Southam Remix)
   https://www.youtube.com/watch?v=UtilLV50eE8
** Em về tinh khôi - Tạ Quang Thắng
https://www.youtube.com/watch?v=GuiuiVnh6WM
** Chiều nay không có mưa bay - Trung Quân Idol [Video Lyrics]
   https://www.youtube.com/watch?v=0yGNjxPI3lE
** [Clip] Dòng thời gian - Nguyễn Hải Phong
   https://www.youtube.com/watch?v=qHVPotIB-kw
** Ca Dao Em Và Tôi - Quang Linh [Official]
   https://www.youtube.com/watch?v=5kxvghaHkmA
** Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)
   https://www.youtube.com/watch?v=pRpeEdMmmQ0
** Kimi no Na wa.『君の名は。』Official MV - Sparkle your name
   https://www.youtube.com/watch?v=e3Ze62AL9r0
** 1 Phút - Andiez「Lyrics」
   https://www.youtube.com/watch?v=o5IXgZVmV6U
** Spirited Away (2001) - The Name of Life (Instrumental piano) Inochi No Namae いのちの名前
   https://www.youtube.com/watch?v=ImPM5IDIYPs
** Kiss the Rain - Yiruma
   https://www.youtube.com/watch?v=so6ExplQlaY
** Yiruma - Moonlight
   https://www.youtube.com/watch?v=99GyFmnH59s
** 熊木杏里 - 風の記憶 / Kaze no Kioku - Anri Kumaki (Bài hát tiếng nhật "ký ức của gió")
   https://www.youtube.com/watch?v=2EibV1kMLSQ
** Enya - Only Time (Official Music Video)
   https://www.youtube.com/watch?v=7wfYIMyS_dI
** When Stars and Salt collide - Coldplay, A Sky Full of Stars (piano/cello cover)- The Piano Guys
   https://www.youtube.com/watch?v=qrHFg47Mopk
** Moby - Everloving
   https://www.youtube.com/watch?v=atyvdC15HFA
** We Found Love - Lindsey Stirling (VenTribe)
   https://www.youtube.com/watch?v=0g9poWKKpbU
** Hallelujah on a Harp - Leonard Cohen Tribute
   https://www.youtube.com/watch?v=WEK4hw7hMgI
* 2
** Bài Ka Tuổi Trẻ Official Music Video TamKa PKL Khiêm Nguyễn
https://www.youtube.com/watch?v=iExXmRq82Fc
** Quê nhà - Quang Linh
   https://www.youtube.com/watch?v=TZ5_JXrFijU
** Tan Biến - Nguyễn Hải Phong
   https://www.youtube.com/watch?v=IL0GgIeN9T0
** Foster The People - Houdini (Video)
   https://www.youtube.com/watch?v=_GMQLjzVGfw
** Owl City & Carly Rae Jepsen - Good Time
https://www.youtube.com/watch?v=H7HmzwI67ec
** K'NAAN - Wavin' Flag (Coca-Cola Celebration Mix)
   https://www.youtube.com/watch?v=WTJSt4wP2ME
** Cũng đành thôi ‣ Đức Phúc「Lyric Video」| bimm
https://www.youtube.com/watch?v=Qs-XcmaxaLw
** LẠ LÙNG / Vũ. (Original)
   https://www.youtube.com/watch?v=F5tS5m86bOI
** [Vietsub + Kara] Khi Em Cô Đơn Em Nhớ Ai (当你孤单你会想起谁) - Trương Đông Lương
   https://www.youtube.com/watch?v=UKEK5WbW0SY
** [Vietsub by JiWonderland] Please tell me why - Freestyle
   https://www.youtube.com/watch?v=hnc_qF-WnmI
** Lost Frequencies - Are You With Me (Official Music Video)
   https://www.youtube.com/watch?v=VjHMDlAPMUw
** Khánh Ly - Cát bụi
   https://www.youtube.com/watch?v=qtEh7--fHIM
** Snow Patrol - Chasing Cars
   https://www.youtube.com/watch?v=GemKqzILV4w
** 【LIVE】Kana Hanazawa - flattery?
   https://www.youtube.com/watch?v=zA5nCExGRxo
** Jason Mraz - I'm Yours [Official Video]
   https://www.youtube.com/watch?v=EkHTsc9PU2A
** Ed Sheeran - The A Team [Official Video]
   https://www.youtube.com/watch?v=UAWcs5H-qgQ
** Moby - Porcelain
   https://www.youtube.com/watch?v=FAYHTES4whs
** Owl City - Fireflies
   https://www.youtube.com/watch?v=psuRGfAaju4
** 周杰倫 - 稻香 KTV Hương Lúa
   https://www.youtube.com/watch?v=cGJyOxLTebg
** Coldplay - Up&Up (Official Video)
   https://www.youtube.com/watch?v=BPNTC7uZYrI
** [Vietsub | Hán Việt] Tiêu Dao Tuyệt Nhất - Trương Tây (Ost Như Ý Cát Tường 2003)
   https://www.youtube.com/watch?v=3-4sE1GN8ss
* 3
** We The Kings - Sad Song (Lyric Video) ft. Elena Coats
   https://www.youtube.com/watch?v=BZsXcc_tC-o
** Pharrell Williams - Happy
   https://www.youtube.com/watch?v=ZbZSe6N_BXs
** Carly Rae Jepsen - Call Me Maybe
   https://www.youtube.com/watch?v=fWNaR-rxAic
** [Lyric+Vietsub YANST] Oah (Offical Video) - Alexander Rybak
   https://www.youtube.com/watch?v=4a0Xel0ZBlE
** Sia - Cheap Thrills (Lyric Video) ft. Sean Paul
   https://www.youtube.com/watch?v=nYh-n7EOtMA
** [Lyric+Vietsub YANST] La La Love On My Mind - Ann Winsborn
   https://www.youtube.com/watch?v=K3CHy4_K1gE
** [HD 720p] Yêu Dấu Theo Gió Bay - Hiền Thục
https://www.youtube.com/watch?v=r_Gx4fI7zNM
** Mad World - Gary Jules
   https://www.youtube.com/watch?v=4N3N1MlvVc4
** Pharrell Williams - Freedom
   https://www.youtube.com/watch?v=LlY90lG_Fuw
** Chia Tay - Bùi Anh Tuấn (Official Music Video)
   https://www.youtube.com/watch?v=OdE8pYLJh1c
** Holly Henry - Seven Nation Army (TEEMID Cover) ~Faker không giấu nổi vẻ tự hào khi hoàn thành công trình này~
   https://www.youtube.com/watch?v=hTb6ClME6Eg
** Natural Blues. Moby.
   https://www.youtube.com/watch?v=JNWhOJSzZ0M
** Bag Raiders - Shooting Stars
   https://www.youtube.com/watch?v=feA64wXhbjo
** [MV][Kill Me, Heal Me OST] Auditory Hallucination 환청 (ENG+Rom+Han.SUB.) Jang Jae In
   https://www.youtube.com/watch?v=Gg0P9yd0noE
** [Vietsub] The Day You Went Away - M2M.mkv
   https://www.youtube.com/watch?v=L66bOF3dUYs
** Coldplay - Ink (Official Fans' Cut)
   https://www.youtube.com/watch?v=gKM15TaKLUI
* 4
** DAYDREAMS | Soobin Hoàng Sơn ft. BigDaddy | Nhạc trẻ hay tuyển chọn
   https://www.youtube.com/watch?v=o0GYK5Whk80
** Seafret - Oceans
   https://www.youtube.com/watch?v=aqsL0QQaSP4
** Seafret - Give Me Something
   https://www.youtube.com/watch?v=NhK4kGdio6E
** Nhac Phim - Ngoi Nha Hanh Phuc Han Quoc.flv
https://www.youtube.com/watch?v=LbJdIdo6BEI
** Alizée - La Isla Bonita
   https://www.youtube.com/watch?v=xq-aTe77bkA
** 1. Blue Swede - Hooked on a Feelingj
   https://www.youtube.com/watch?v=NrI-UBIB8Jk
** Aimer - Kataomoi
https://www.youtube.com/watch?v=zSOJk7ggJts
** Enrique Iglesias - I'm A Freak ft. Pitbull
https://www.youtube.com/watch?v=YUiVIPgJA0o
** Fuck You - Lily Allen (Lyrics)
   https://www.youtube.com/watch?v=OK4fJhbRL1g
** TOULIVER X LÊ HIẾU X SOOBIN HOÀNG SƠN - NGÀY MAI EM ĐI 2017 | OFFICIAL LYRIC VIDEO
   https://www.youtube.com/watch?v=z5Jc7KiTLbs
** Jason Mraz & Colbie Caillat - Lucky [Official Video]
   https://www.youtube.com/watch?v=acvIVA9-FMQ
** Of Monsters And Men - Dirty Paws (Official Lyric Video)
   https://www.youtube.com/watch?v=mCHUw7ACS8o
** Of Monsters And Men - Little Talks (Official Video)
   https://www.youtube.com/watch?v=ghb6eDopW8I
** [MV] 케이윌(K.will) - 이러지마 제발 (Please don't...)
   https://www.youtube.com/watch?v=PdUiCJnRptk
** Adele - When We Were Young (Live at The Church Studios)
   https://www.youtube.com/watch?v=DDWKuo3gXMQ
** Coldplay - All I Can Think About Is You (Official Lyric Video)
   https://www.youtube.com/watch?v=KnLNG0WnGsI
** Fun.: Some Nights [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=qQkBeOisNM0
* 5
** Rudimental - Waiting All Night ft. Ella Eyre [Official Video]
   https://www.youtube.com/watch?v=M97vR2V4vTs
** Avicii - The Nights
   https://www.youtube.com/watch?v=UtF6Jej8yb4
** Fun.: We Are Young ft. Janelle Monáe [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=Sv6dMFF_yts
** Maroon 5 - Payphone (Explicit) ft. Wiz Khalifa
   https://www.youtube.com/watch?v=KRaWnd3LJfs
** Snow Patrol - The Sunlight Through the Flags (Part 2 of The Lightning Strike)
   https://www.youtube.com/watch?v=cHl6dLaUAjk
** Jang Nara Sweet Dream MV
https://www.youtube.com/watch?v=ITJlByULnhY
** Lost Frequencies feat. Janieck Devy - Reality (Official Music Video)
   https://www.youtube.com/watch?v=ilw-qmqZ5zY
** Alan Walker - The Spectre
   https://www.youtube.com/watch?v=wJnBTPUQS5A
** Tez Cadey - Seve
   https://www.youtube.com/watch?v=t5747BhezKM
** Selena Gomez - Bad Liar
   https://www.youtube.com/watch?v=NZKXkD6EgBk
** Stoto - Still Can't Sleep (Original Mix)
   https://www.youtube.com/watch?v=UAHaxlCe29E
** Vitas - Opera N2
   https://www.youtube.com/watch?v=tITWIcNeTjw
** Of Monsters and Men - King And Lionheart (Official Video)
   https://www.youtube.com/watch?v=A76a_LNIYwE
** [Vietsub | Hán Việt] Đồng Thoại - Quang Lương (Music Gift For You No.2)
   https://www.youtube.com/watch?v=DjOEbfGyANA
** Sứ thanh hoa 青花瓷 - Jay Chou
   https://www.youtube.com/watch?v=CZ78y__MIzM
** [Vietsub][HD] Endless Love (The Myth Theme Song) - Jackie Chan & Kim Hee Sun
   https://www.youtube.com/watch?v=EwuyNZDojg8
* 6
** 7. Jackson 5 - I Want You Back
   https://www.youtube.com/watch?v=DGDyAb6pePo
** Lucky Twice- Lucky (I'm so lucky lucky!) with lyrics on screen
   https://www.youtube.com/watch?v=MBtLD7IbsEA
** Mc Mong ft . Mellow - Sick Enough To Die
   https://www.youtube.com/watch?v=fwS74MG5JMg
** T-ara & Supernova(티아라 & 초신성) _ TTL (TIME TO LOVE) MV
https://www.youtube.com/watch?v=NFFgRRLInD4
** Merk & Kremont - Sad Story (Out Of Luck) [Official Music Video]
   https://www.youtube.com/watch?v=8GotXeCwUnc
** P!nk - Blow Me (One Last Kiss)
   https://www.youtube.com/watch?v=3jNlIGDRkvQ
** Halsey - Colors
   https://www.youtube.com/watch?v=JGulAZnnTKA
** Mirrors - Justin Timberlake
*** (Boyce Avenue feat. Fifth Harmony cover) on Apple & Spotify
    https://www.youtube.com/watch?v=fvEZUbzqqyM
*** Justin Timberlake - Mirrors
    https://www.youtube.com/watch?v=uuZE_IRwLNI
** Vietsub | Hán Việt] Song Phi - Hà Nhuận Đông (Ost Lương Sơn Bá Chúc Anh Đài 2007)
   https://www.youtube.com/watch?v=Vaclu3ZmHlQ
** [MV Full HD] Those Years - Hu Xia [Vietsub + Kara FX] (You Are the Apple of My Eye's OST)
   https://www.youtube.com/watch?v=UBehxEC8c-4
** Of Monsters And Men - Love Love Love (Official Lyric Video)
   https://www.youtube.com/watch?v=beiPP_MGz6I
** Gotye - Somebody That I Used To Know (feat. Kimbra) - official video
   https://www.youtube.com/watch?v=8UVNT4wvIGY
** B.o.B - Airplanes ft. Hayley Williams
   https://www.youtube.com/watch?v=eVcvBmFF_lU
* 7
** TOULIVER X BINZ - THEY SAID [ OFFICIAL MV ]
https://www.youtube.com/watch?v=XdBsAXOxYfo
** The Kooks - Bad Habit
   https://www.youtube.com/watch?v=3tUh-x-fp8Q
** Ngẫu Hứng Hoaprox
   https://www.youtube.com/watch?v=vtskUyVJYVA
** [Official Video]5PM-Liêu Anh Tuấn.mp4
   https://www.youtube.com/watch?v=HBVBc5LHxRk
** Foster The People - Pumped up Kicks
   https://www.youtube.com/watch?v=SDTZ7iX4vTQ
** Zara Larsson - Lush Life
   https://www.youtube.com/watch?v=tD4HCZe-tew
** The Killers - Just Another Girl
   https://www.youtube.com/watch?v=3BwzP1laWkQ
** The Killers - Human
   https://www.youtube.com/watch?v=RIZdjT1472Y
** [Vietsub+Kara] 5cm/s AMV - Sakura anata ni deaete yokatta
   https://www.youtube.com/watch?v=WAT-Gy6QsTY
** Adele - Set Fire To The Rain (Live at The Royal Albert Hall)
   https://www.youtube.com/watch?v=Ri7-vnrJD3k
** Adele - Rolling in the Deep
   https://www.youtube.com/watch?v=rYEDA3JcQqw
** [Vietsub | Hán Việt] Kiếm Hồn - Lý Vĩ (Ost Tân Anh Hùng Xạ Điêu 2017)
   https://www.youtube.com/watch?v=4MOsX9sE1VA
** Descendants Of The Sun-[HD] OST||Once Again- Kim Na-Young ft Mad Clown
   https://www.youtube.com/watch?v=PKIU4ebQxOA
** TAEYANG - 눈,코,입 (EYES, NOSE, LIPS) M/V
   https://www.youtube.com/watch?v=UwuAPyOImoI
* 8
** Britney Spears - ...Baby One More Time
https://www.youtube.com/watch?v=C-u5WLJ9Yk4
** David Guetta & Showtek - Bad ft.Vassy (Lyrics Video)
   https://www.youtube.com/watch?v=oC-GflRB0y4
** Calvin Harris - Blame ft. John Newman
   https://www.youtube.com/watch?v=6ACl8s_tBzE
** Calvin Harris - Summer
   https://www.youtube.com/watch?v=ebXbLfLACGM
** Swedish House Mafia - Don't You Worry Child ft. John Martin
   https://www.youtube.com/watch?v=1y6smkh6c-0
** Far East Movement - Like A G6 ft. The Cataracs, DEV
   https://www.youtube.com/watch?v=w4s6H4ku6ZY
** The Killers - Miss Atomic Bomb
   https://www.youtube.com/watch?v=Qok9Ialei4c
** Snow Patrol - The Lightning Strike (What If This Storm Ends?)
   https://www.youtube.com/watch?v=S0BDS0-ZwOw
** will.i.am - #thatPOWER ft. Justin Bieber
   https://www.youtube.com/watch?v=DGIgXP9SvB8
** Austin Mahone - Mmm Yeah ft. Pitbull
   https://www.youtube.com/watch?v=MMAppa1cAVo
** CloZee - Secret Place
   https://www.youtube.com/watch?v=soLrXM0EQ8c
** Bệnh Của Anh - Khói [Lyric Video]
   https://www.youtube.com/watch?v=FFwasFKSjSg
** Call Me - Koo [Lyric Video] ( Prod. Danny EB )
   https://www.youtube.com/watch?v=FWkW-YkzCJ4
** [Full MV] 2PM & SNSD - Caribbean Bay CABI Song
   https://www.youtube.com/watch?v=EiheWWaWApc
** DARA - KISS M/V
   https://www.youtube.com/watch?v=ZAqiMCp9zrI
** Imagine Dragons - Whatever It Takes
   https://www.youtube.com/watch?v=gOsM-DYAEhY
** Maroon 5 - Wait
   https://www.youtube.com/watch?v=4uTNVumfm84
** G-DRAGON - HEARTBREAKER M/V
   https://www.youtube.com/watch?v=LOXEVd-Z7NE
** BIGBANG - LIES(거짓말) M/V
   https://www.youtube.com/watch?v=2Cv3phvP8Ro
** GD X TAEYANG - GOOD BOY M/V
   https://www.youtube.com/watch?v=1ZRb1we80kM
** Justin Timberlake - Suit & Tie (Official) ft. JAY Z
   https://www.youtube.com/watch?v=IsUsVbTj2AY
** Moby - Lift Me Up
   https://www.youtube.com/watch?v=CWGNA3u4-Sg
* 9
** Bon Jovi - It's My Life
https://www.youtube.com/watch?v=vx2u5uUu3D E
** Unknown Brain - Superhero (feat. Chris Linton) [NCS Release]
   https://www.youtube.com/watch?v=LHvYrn3FAgI
** The Orb - Little Fluffy Clouds
   https://www.youtube.com/watch?v=FHixChYgGRI
** Avicii - Waiting For Love
   https://www.youtube.com/watch?v=cHHLHGNpCSA
** DVBBS & Borgeous - TSUNAMI (Original Mix)
   https://www.youtube.com/watch?v=0EWbonj7f18
** Khu Tao Song -Wowy+Karik (OFFICIAL VIDEO HD) ©SouthGanz 2010
   https://www.youtube.com/watch?v=UZ2M12BeKX4
** Lorde - Royals (US Version)
   https://www.youtube.com/watch?v=nlcIKh6sBtc
** MACKLEMORE & RYAN LEWIS - CAN'T HOLD US FEAT. RAY DALTON (OFFICIAL MUSIC VIDEO)
   https://www.youtube.com/watch?v=2zNSgSzhBfM
** Lemaitre - Higher ft. Maty Noyes
   https://www.youtube.com/watch?v=bsENfTmAdeI
** Skrillex & Damian "Jr. Gong" Marley - Make It Bun Dem [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=BGpzGu9Yp6Y
** CAZZETTE - She Wants Me Dead (CAZZETTE vs. AronChupa) [Official Video] ft. The High
   https://www.youtube.com/watch?v=FHccClTAdzc
** twenty one pilots: Stressed Out [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=pXRviuL6vMY
** Nelly - Just A Dream
   https://www.youtube.com/watch?v=N6O2ncUKvlg
** Eminem - Rap God (Explicit)
   https://www.youtube.com/watch?v=XbGs_qK2PQA
** Logan | Way Down We Go | Music Video
   https://www.youtube.com/watch?v=LCkyW7RE6Wk
** Cùng Anh - Ngọc Dolil (VRT Mix)
   https://www.youtube.com/watch?v=V9S5QPbzPoo
** Caravan Palace - Lone Digger
   https://www.youtube.com/watch?v=UbQgXeY_zi4
** Hai Thế Giới full - Wowy & Karik ( Offical Video HD full ) ©SouthGanz Entertainment
   https://www.youtube.com/watch?v=3JLDUJJuVGk
** DEV - Bass Down Low (Explicit) ft. The Cataracs
https://www.youtube.com/watch?v=OOAMfUJ3tsc
* 10
** Martin Garrix - Animals (Official Video)
   https://www.youtube.com/watch?v=gCYcHz2k5x0
** Calvin Harris & Alesso - Under Control ft. Hurts
   https://www.youtube.com/watch?v=yZqmarGShxg
** DJ Tiesto - Welcome To Ibiza
   https://www.youtube.com/watch?v=-JOlwVia1As
** Eminem - Lose Yourself [HD]
   https://www.youtube.com/watch?v=_Yhyp-_hX2s
** Dimitri Vegas, Martin Garrix, Like Mike - Tremor (Official Music Video)
   https://www.youtube.com/watch?v=9vMh9f41pqE
** Requiem For A Dream Full Song HD
   https://www.youtube.com/watch?v=yVIRcnlRKF8
** CAZZETTE - She Wants Me Dead (CAZZETTE vs. AronChupa) [Official Video] ft. The High
   https://www.youtube.com/watch?v=FHccClTAdzc
** The XX - Intro HQ
   https://www.youtube.com/watch?v=AZ1pHmWhIuY
** clubbed to death - Matrix soundtrack
   https://www.youtube.com/watch?v=XbxZargtXug
** In The End (Official Video) - Linkin Park
   https://www.youtube.com/watch?v=eVTXPUF4Oz4
** Numb (Official Video) - Linkin Park
   https://www.youtube.com/watch?v=kXYiU_JCYtU
** Skrillex & Damian "Jr. Gong" Marley - Make It Bun Dem [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=BGpzGu9Yp6Y
** Avicii - Levels
   https://www.youtube.com/watch?v=_ovdm2yX4MA
