* 1
** Coldplay - O (Fly On) - Extended
https://www.youtube.com/watch?v=eAbDNUj8pxo
** Ben Howard - Promise
https://www.youtube.com/watch?v=CVUOTzoVeZA
** Chopin - Nocturne op.9 No.2
https://www.youtube.com/watch?v=9E6b3swbnWg
** Above & Beyond Acoustic - "Good For Me" Live from Porchester Hall (Official)
   https://www.youtube.com/watch?v=ifPsVauGgnY
** AsaChan - 'Minkara'
   https://www.youtube.com/watch?v=Uvt5TZy0aAc
** Leaving On A Jet Plane - John Denver (cover) | Reneé Dominique
   https://www.youtube.com/watch?v=aLVlS-mHQbw
** Andreas Bourani - Auf anderen Wegen (Official Video)
   https://www.youtube.com/watch?v=m-Ik3yy728Y
** La Vie En Rose
   https://www.youtube.com/watch?v=3Ba_WoSZXvw
** The Band Perry - If I Die Young
   https://www.youtube.com/watch?v=7NJqUN9TClM
** The Lion King (1994): "Can You Feel the Love Tonight" by Elton John (with lyrics)
   https://www.youtube.com/watch?v=jgMkEKcWj94
** Remember when - Alan Jackson
   https://www.youtube.com/watch?v=TOmZ66lIzJA
** Coldplay - Fix You
   https://www.youtube.com/watch?v=k4V3Mo61fJM
** Christina Perri - Arms [Official Music Video]
   https://www.youtube.com/watch?v=MeW0Sl0tNS8
** Christina Perri - Something About December [Official Video]
   https://www.youtube.com/watch?v=OR2LXXIX8ro
** Lenka - The Show (New Version)
   https://www.youtube.com/watch?v=elsh3J5lJ6g
** Passenger | Let Her Go (Official Video)
   https://www.youtube.com/watch?v=RBumgq5yVrA
** 川嶋あい / 旅立ちの日に・・・（Lyrics）
   https://www.youtube.com/watch?v=DlO308doIyU
** 熊木杏里 - 「桜」（コブクロ 「桜」 のカバー）
   https://www.youtube.com/watch?v=NAnBxv8hJU0
** Hollow Coves - The Woods (Rami & Mitchell Southam Remix)
   https://www.youtube.com/watch?v=UtilLV50eE8
** Em về tinh khôi - Tạ Quang Thắng
   https://www.youtube.com/watch?v=GuiuiVnh6WM
** Chiều nay không có mưa bay - Trung Quân Idol [Video Lyrics]
   https://www.youtube.com/watch?v=0yGNjxPI3lE
** [Clip] Dòng thời gian - Nguyễn Hải Phong
   https://www.youtube.com/watch?v=qHVPotIB-kw
** Ca Dao Em Và Tôi - Quang Linh [Official]
   https://www.youtube.com/watch?v=5kxvghaHkmA
** Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)
   https://www.youtube.com/watch?v=pRpeEdMmmQ0
** Kimi no Na wa.『君の名は。』Official MV - Sparkle your name
   https://www.youtube.com/watch?v=e3Ze62AL9r0
** 1 Phút - Andiez「Lyrics」
   https://www.youtube.com/watch?v=o5IXgZVmV6U
** Spirited Away (2001) - The Name of Life (Instrumental piano) Inochi No Namae いのちの名前
   https://www.youtube.com/watch?v=ImPM5IDIYPs
** Kiss the Rain - Yiruma
   https://www.youtube.com/watch?v=so6ExplQlaY
** Yiruma - Moonlight
   https://www.youtube.com/watch?v=99GyFmnH59s
** 熊木杏里 - 風の記憶 / Kaze no Kioku - Anri Kumaki (Bài hát tiếng nhật "ký ức của gió")
   https://www.youtube.com/watch?v=2EibV1kMLSQ
** Enya - Only Time (Official Music Video)
   https://www.youtube.com/watch?v=7wfYIMyS_dI
** When Stars and Salt collide - Coldplay, A Sky Full of Stars (piano/cello cover)- The Piano Guys
   https://www.youtube.com/watch?v=qrHFg47Mopk
** Moby - Everloving
   https://www.youtube.com/watch?v=atyvdC15HFA
** We Found Love - Lindsey Stirling (VenTribe)
   https://www.youtube.com/watch?v=0g9poWKKpbU
** Hallelujah on a Harp - Leonard Cohen Tribute
   https://www.youtube.com/watch?v=WEK4hw7hMgI
** NELL "지구가 태양을 네번/ Four times around the sun/ 地球が太陽を4 回" Official MV
   https://www.youtube.com/watch?v=g5cVE-i5wHI
** Bèo dạt mây trôi - Anh khang ft Quang Thắng
   https://www.youtube.com/watch?v=dcsGejac-04
** Làng Quan Họ Quê Tôi - Anh Thơ | Nhạc Trữ Tình, Nhạc Quê Hương
   https://www.youtube.com/watch?v=dnoxjgyTXiQ
** [ MV || LYRIC || Kara ] Quê Tôi - Thùy Chi
   https://www.youtube.com/watch?v=v_659RyLbHM
** Giấc Mơ Trưa - Thùy Chi
   https://www.youtube.com/watch?v=9CU0cIEg0j8
* 2
** OneRepublic - Kids (Audio)
https://www.youtube.com/watch?v=AIiTRr4lxZM
** Careless Whisper | George Michael | Lyrics [Kara + Vietsub HD]
   https://www.youtube.com/watch?v=YAHj6mH7z2s
** Five for Fighting - Superman (It's Not Easy)
https://www.youtube.com/watch?v=GRz4FY0ZcwI
** Coldplay - Yellow
https://www.youtube.com/watch?v=yKNxeF4KMsY
** The 1975 - Somebody Else (Official Video)
https://www.youtube.com/watch?v=Bimd2nZirT4
** [OFFICIAL MP3] CÒN TUỔI NÀO CHO EM - MIU LÊ
https://www.youtube.com/watch?v=brhuZ_i60w0
** Cá Hồi Hoang - Có Thể
https://www.youtube.com/watch?v=tUWHyFpnIwE
** #AiChoAi - FloD ft. M! (Giang Nguyen) [ Official Audio]
https://www.youtube.com/watch?v=afNQLlTRvfM
** Màu Xanh Việt Nam - Lương Bằng Qang - [ Lyric ]
   https://www.youtube.com/watch?v=yay2iRapqsk
** Bay Cùng Tình Yêu - Lương Bằng Quang (Album Return)
   https://www.youtube.com/watch?v=41_luxZz8UA
** LEA RUE - Sleep, For The Weak! (Lost Frequencies Remix)
   https://www.youtube.com/watch?v=3dViG52tHI4
** filous - How Hard I Try (feat. James Hersey)
   https://www.youtube.com/watch?v=sb9fHU4d3Ds
** James Hersey - Coming Over (Filous Remix)
   https://www.youtube.com/watch?v=GHoJ9NzP338
** Please tell me why - Free Style ( The Heirs )
   https://www.youtube.com/watch?v=d_M_kizumSQ
** Anh Mơ - Anh Khang (Official Video Clip)
** TAKE A CHANCE ON ME / FRANKIE J / vietsub
   https://www.youtube.com/watch?v=SFf-ufa9MwA
** Owl City - Beautiful Times ft. Lindsey Stirling
   https://www.youtube.com/watch?v=gfA-tPKPoNs
** Star Sky - Final Fantasy XV (Luna & Noctis)
   https://www.youtube.com/watch?v=0EqsxNC7i7Q
** Phil Collins - You'll Be In My Heart
   https://www.youtube.com/watch?v=w0ZHlp6atUQ
** Bee Gees - How Deep Is Your Love (1977)
   https://www.youtube.com/watch?v=XpqqjU7u5Yc
** Bruno Mars Talking to the moon
   https://www.youtube.com/watch?v=J9pXeziqdLc
** Maroon 5 - Daylight (Playing for Change)
   https://www.youtube.com/watch?v=AqR-ElB5kXY
** VIETSUB OST Nữ Nhi Quốc (full) -Trương Lượng Dĩnh & Lý Vinh Hạo - 女儿国-(电影《西游记女儿国》主题曲)
   https://www.youtube.com/watch?v=858zgYTAJq4
** Owl City - Vanilla Twilight
   https://www.youtube.com/watch?v=pIz2K3ArrWk
** Justin Bieber - Mistletoe
   https://www.youtube.com/watch?v=LUjn3RpkcKY
** Justin Bieber - Pray
   https://www.youtube.com/watch?v=o9tJW9MDs2M
** Coldplay - Hypnotised (Official Lyric Video)
   https://www.youtube.com/watch?v=WXmTEyq5nXc
** Coldplay Gravity
   https://www.youtube.com/watch?v=9ZLjiaGJyhI
** Westlife - Nothing's Gonna Change My Love For You [VietSub | Kara Effect | HD]
   https://www.youtube.com/watch?v=dRLq2mc5IZk
** Westlife - Beautiful in White
   https://www.youtube.com/watch?v=XRuDQ6aYeD0
** M2M - Pretty Boy
   https://www.youtube.com/watch?v=-v7ZMOhMONU
** M2M - Mirror, Mirror
   https://www.youtube.com/watch?v=P2vpB3yQuqg
** I Love You || Mr. Siro - [HD Kara+Lyrics]
   https://www.youtube.com/watch?v=yxYMMs_34us
** Ngày mai nắng lên anh sẽ về (Official MV) - HQ
   https://www.youtube.com/watch?v=o-8vj5nzu3c
** KAI ĐINH l ĐIỀU BUỒN NHẤT | OFFICIAL LYRIC VIDEO
   https://www.youtube.com/watch?v=D2g-IY0Uc70
** Mân Côi - Linh Cáo (Lyric Video / TAS Release)
   https://www.youtube.com/watch?v=Ls6EBIR8hDE
** The Killers - Shot At The Night
   https://www.youtube.com/watch?v=X4YK-DEkvcw
** Taylor Swift - Back To December
   https://www.youtube.com/watch?v=eocfbbyIUn8
** Taylor Swift - Begin Again
   https://www.youtube.com/watch?v=cMPEd8m79Hw
** Taylor Swift - You Belong With Me
   https://www.youtube.com/watch?v=VuNIsY6JdUw
** Coldplay & Big Sean - Miracles (Someone Special) - Official Lyric Video
   https://www.youtube.com/watch?v=z9BPMjL44Aw
** Imagine Dragons - On Top Of The World (Official Music Video)
   https://www.youtube.com/watch?v=w5tWYmIOWGk
** OneRepublic - Good Life
   https://www.youtube.com/watch?v=jZhQOvvV45w
** Coldplay - Hymn For The Weekend (Official Video)
   https://www.youtube.com/watch?v=YykjpeuMNEk
** Chân ngắn | Cẩm Vân Ft TMT (Video lyric - HD)
** Dido - Thank You (Official Video)
   https://www.youtube.com/watch?v=1TO48Cnl66w
** Sting - Shape of My Heart (Leon)
   https://www.youtube.com/watch?v=QK-Z1K67uaA
** Christina Perri - A Thousand Years [Official Music Video]
   https://www.youtube.com/watch?v=rtOvBOTyX00
** Bài Ka Tuổi Trẻ Official Music Video TamKa PKL Khiêm Nguyễn
   https://www.youtube.com/watch?v=iExXmRq82Fc
** Quê nhà - Quang Linh
   https://www.youtube.com/watch?v=TZ5_JXrFijU
** Tan Biến - Nguyễn Hải Phong
   https://www.youtube.com/watch?v=IL0GgIeN9T0
** Foster The People - Houdini (Video)
   https://www.youtube.com/watch?v=_GMQLjzVGfw
** Owl City & Carly Rae Jepsen - Good Time
   https://www.youtube.com/watch?v=H7HmzwI67ec
** K'NAAN - Wavin' Flag (Coca-Cola Celebration Mix)
   https://www.youtube.com/watch?v=WTJSt4wP2ME
** Cũng đành thôi ‣ Đức Phúc「Lyric Video」| bimm
   https://www.youtube.com/watch?v=Qs-XcmaxaLw
** LẠ LÙNG / Vũ. (Original)
   https://www.youtube.com/watch?v=F5tS5m86bOI
** [Vietsub + Kara] Khi Em Cô Đơn Em Nhớ Ai (当你孤单你会想起谁) - Trương Đông Lương
   https://www.youtube.com/watch?v=UKEK5WbW0SY
** [Vietsub by JiWonderland] Please tell me why - Freestyle
   https://www.youtube.com/watch?v=hnc_qF-WnmI
** Lost Frequencies - Are You With Me (Official Music Video)
   https://www.youtube.com/watch?v=VjHMDlAPMUw
** Khánh Ly - Cát bụi
   https://www.youtube.com/watch?v=qtEh7--fHIM
** Snow Patrol - Chasing Cars
   https://www.youtube.com/watch?v=GemKqzILV4w
** 【LIVE】Kana Hanazawa - flattery?
   https://www.youtube.com/watch?v=zA5nCExGRxo
** Jason Mraz - I'm Yours [Official Video]
   https://www.youtube.com/watch?v=EkHTsc9PU2A
** Ed Sheeran - The A Team [Official Video]
   https://www.youtube.com/watch?v=UAWcs5H-qgQ
** Moby - Porcelain
   https://www.youtube.com/watch?v=FAYHTES4whs
** Owl City - Fireflies
   https://www.youtube.com/watch?v=psuRGfAaju4
** 周杰倫 - 稻香 KTV Hương Lúa
   https://www.youtube.com/watch?v=cGJyOxLTebg
** Coldplay - Up&Up (Official Video)
   https://www.youtube.com/watch?v=BPNTC7uZYrI
** [Vietsub | Hán Việt] Tiêu Dao Tuyệt Nhất - Trương Tây (Ost Như Ý Cát Tường 2003)
   https://www.youtube.com/watch?v=3-4sE1GN8ss
** Coldplay - Army of one
   f
   https://www.youtube.com/watch?v=7tPxHoZVgF0
** Andreas Bourani - Auf uns (Official Video)
   https://www.youtube.com/watch?v=k9EYjn5f_nE
** Rhythm Of The Rain | The Cascades | Lyrics [Kara + Vietsub HD]
   https://www.youtube.com/watch?v=P7T-PJD_M3U
** Capital Cities - One Minute More (Official Video)
   https://www.youtube.com/watch?v=w0IIYU9om_k
* 3
** Olly Murs - That Girl (Lyrics) (Vietsub) - TIKTOK
https://www.youtube.com/watch?v=P_mud10R-rA
** ＲＡＩＮ (Saturday Night Lights by Dragon Roots)
https://www.youtube.com/watch?v=JE3vqqocqwU
** Taylor Swift - Delicate
https://www.youtube.com/watch?v=tCXGJQYZ9JA
** [Kara] Làm ơn - Trần Trung Đức
https://www.youtube.com/watch?v=PSBAast7zqU
** Passenger | Hell Or High Water (Official Video)
   https://www.youtube.com/watch?v=zgDbp5C74sU
** Rachel Platten - Fight Song (Official Video)
https://www.youtube.com/watch?v=xo1VInw-SKc
** The Chemical Brothers - Wide Open ft. Beck
https://www.youtube.com/watch?v=BC2dRkm8ATU
** [Engsub\Vietsub - Kara] Bỗng Dưng Muốn Khóc - Minh Thư (Suddenly Tear)
https://www.youtube.com/watch?v=fZFfeP9hvoE
** Owl City - Shooting Star
https://www.youtube.com/watch?v=Uq8Dgcy4MDY
** Above & Beyond Acoustic - "You Got To Go" Live from Porchester Hall (Official)
   https://www.youtube.com/watch?v=MJQE4pOgiPg
** Tạ Quang Thắng - Vội Vàng (Official Music Video)
   https://www.youtube.com/watch?v=R43xOUlRHWc
** Afrojack - Ten Feet Tall (Lyric Video) ft. Wrabel
   https://www.youtube.com/watch?v=bltr_Dsk5EY
** Calvin Harris - Feel So Close
   https://www.youtube.com/watch?v=dGghkjpNCQ8
** Ellie Goulding - Lights
   https://www.youtube.com/watch?v=0NKUpo_xKyQ
** One Direction - More Than This (Up All Night: The Live Tour)
   https://www.youtube.com/watch?v=b-RQIN3wo5U
** Bruno Mars - Marry You (Lyrics) HD
   https://www.youtube.com/watch?v=Zlv1rdcpS9M
** Bruno Mars - The Lazy Song [ALTERNATE OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=dULOjT9GYdQ
** Maroon 5 - Won't Go Home Without You
   https://www.youtube.com/watch?v=VlMEGBsw6j8
** Maroon 5 - Goodnight Goodnight
   https://www.youtube.com/watch?v=uNSBq6hvU1s
** Shakira - Can't Remember to Forget You ft. Rihanna
   https://www.youtube.com/watch?v=o3mP3mJDL2k
** Shakira - La La La (Brazil 2014) ft. Carlinhos Brown
   https://www.youtube.com/watch?v=7-7knsP2n5w
** Welcome to Beijing -[HD]
   https://www.youtube.com/watch?v=Xj8R7bEGK4w
** Kidswaste - Free
   https://www.youtube.com/watch?v=peP2AcgjyHE
** Marcapasos - Aicha (Official Video HD) johanna Kleen﻿ 
   https://www.youtube.com/watch?v=O0v7sd3zdbo
** Frank Sinatra-Killing me softly
   https://www.youtube.com/watch?v=8tbP3f3i03E
** Feldberg - You and Me
   https://www.youtube.com/watch?v=uDTaxJxZIX0
** Lyrics || Người Con Gái Ta Thương - Hà Anh Tuấn
   https://www.youtube.com/watch?v=LVQxfALfTe4
** Halsey - Ghost
   https://www.youtube.com/watch?v=ao4o-XRU_KM
** Mr. Probz - Nothing Really Matters (Afrojack Remix)
   https://www.youtube.com/watch?v=M_lIi1hb6WU
** Simba- You Raise Me Up
   https://www.youtube.com/watch?v=CjW77WXPw8Y
** Jim Croce -Time In A Bottle (Lyrics)
   https://www.youtube.com/watch?v=dO1rMeYnOmM   origin
   https://www.youtube.com/watch?v=AnWWj6xOleY
** Lenka - Blue Skies
   https://www.youtube.com/watch?v=ztO3Rjqxcho
** Dido - White Flag (Official Video)
   https://www.youtube.com/watch?v=j-fWDrZSiZs
** Thư Chưa Gửi Anh | OFFICIAL MV | Hòa Minzy
   https://www.youtube.com/watch?v=suHyMFtWtFw
** [MV Fanmade] Xe Đạp - Thùy Chi ft. M4U
   https://www.youtube.com/watch?v=6KJrNWC0tfw
** Lenka - Trouble Is A Friend (YouTube Version)
   https://www.youtube.com/watch?v=QHpvlr_kG6U
** Daniel Powter - Bad Day (Official Music Video)
   https://www.youtube.com/watch?v=gH476CxJxfg
** Justin Bieber - Love Yourself (PURPOSE : The Movement)
   https://www.youtube.com/watch?v=oyEuk8j8imI
** Coldplay - A Head Full Of Dreams (Official Video)
   https://www.youtube.com/watch?v=vGZMvV9KBp8
** Kygo - Raging ft. Kodaline
   https://www.youtube.com/watch?v=ZhzN7-Q00KU
** Kygo & Ellie Goulding - First Time
   https://www.youtube.com/watch?v=OlH1RCs96JA
** Kygo - Stay ft. Maty Noyes
   https://www.youtube.com/watch?v=z9porfO8C_Q
** Bastille - Pompeii
   https://www.youtube.com/watch?v=F90Cw4l-8NY
** Kelly Clarkson - Stronger (What Doesn't Kill You)
   https://www.youtube.com/watch?v=Xn676-fLq7I
** LEE HI (이하이) - ROSE M/V
   https://www.youtube.com/watch?v=Ff_SuAzll90
** Taeyang ~ I Need a Girl (Dance Ver.) [MV] [ENG SUB]
   https://www.youtube.com/watch?v=BuuiBjL09KY
** Anna Kendrick - Cups (When I'm Gone) (Official Video) [Lyrics + Sub Español]
   https://www.youtube.com/watch?v=2oFEMmBuUVo
** Creep - Radiohead
   https://www.youtube.com/watch?v=lZiNtbgm9oM
** 2AM - JustaTee, BigDaddy [ Lyrics MV ]
   https://www.youtube.com/watch?v=vFgMYWDPg3A
** "Talk to You" - JayTee ft. Mr.A , Ellian , Bueno , Mr.T & Trang Rin
   https://www.youtube.com/watch?v=EFsqoXvpBnQ
** Hoa Sữa - JustaTee, Touliver, MR.A và Kim JoJo [Fan Made HD]
   https://www.youtube.com/watch?v=XViTvrEH1XQ
** We The Kings - Sad Song (Lyric Video) ft. Elena Coats
   https://www.youtube.com/watch?v=BZsXcc_tC-o
** Pharrell Williams - Happy
   https://www.youtube.com/watch?v=ZbZSe6N_BXs
** B.O.B Ft. Bruno Mars - Nothing On You [Lyrics]
   https://www.youtube.com/watch?v=6IRcX6poKT0
** Bruno Mars - It Will Rain [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=W-w3WfgpcGg
** Carly Rae Jepsen - Call Me Maybe
   https://www.youtube.com/watch?v=fWNaR-rxAic
** [Lyric+Vietsub YANST] Oah (Offical Video) - Alexander Rybak
   https://www.youtube.com/watch?v=4a0Xel0ZBlE
** Sia - Cheap Thrills (Lyric Video) ft. Sean Paul
   https://www.youtube.com/watch?v=nYh-n7EOtMA
** [Lyric+Vietsub YANST] La La Love On My Mind - Ann Winsborn
   https://www.youtube.com/watch?v=K3CHy4_K1gE
** [HD 720p] Yêu Dấu Theo Gió Bay - Hiền Thục
   https://www.youtube.com/watch?v=r_Gx4fI7zNM
** Mad World - Gary Jules
   https://www.youtube.com/watch?v=4N3N1MlvVc4
** Pharrell Williams - Freedom
   https://www.youtube.com/watch?v=LlY90lG_Fuw
** Chia Tay - Bùi Anh Tuấn (Official Music Video)
   https://www.youtube.com/watch?v=OdE8pYLJh1c
** Holly Henry - Seven Nation Army (TEEMID Cover) ~Faker không giấu nổi vẻ tự hào khi hoàn thành công trình này~
   https://www.youtube.com/watch?v=hTb6ClME6Eg
   https://www.youtube.com/watch?v=GYFJjwXtsU4
** Natural Blues. Moby.
   https://www.youtube.com/watch?v=JNWhOJSzZ0M
** Bag Raiders - Shooting Stars
   https://www.youtube.com/watch?v=feA64wXhbjo
** [MV][Kill Me, Heal Me OST] Auditory Hallucination 환청 (ENG+Rom+Han.SUB.) Jang Jae In
   https://www.youtube.com/watch?v=Gg0P9yd0noE
** [Vietsub] The Day You Went Away - M2M.mkv
   https://www.youtube.com/watch?v=L66bOF3dUYs
** Coldplay - Ink (Official Fans' Cut)
   https://www.youtube.com/watch?v=gKM15TaKLUI
** Coldplay - All Your Friends (Official Video)
   https://www.youtube.com/watch?v=E5a51OonZDE
** Britney Spears - Everytime
   https://www.youtube.com/watch?v=8YzabSdk7ZA
* 4
** Clara Mae - I'm Not Her (Official Video)
   https://www.youtube.com/watch?v=iUNxOzxPEVI
** Hẹn Một Mai | Bùi Anh Tuấn | Official MV | Nhạc trẻ hay mới nhất
https://www.youtube.com/watch?v=pX6nutvtDnI
** Michael Learns To Rock - Take Me To Your Heart [Official Video] (with Lyrics Closed Caption)
https://www.youtube.com/watch?v=TbLT12eg-lw
** BÍCH PHƯƠNG - Bùa Yêu (Official M/V)
https://www.youtube.com/watch?v=FkOt19CUC30
** Coldplay - Another's Arms Live 2014 Ghost stories
https://www.youtube.com/watch?v=dJBqwwW4BD8
** Carly Rae Jepsen - Tonight I'm Getting Over You
https://www.youtube.com/watch?v=cBOE1aUNZVo
** Chính em - Lương Bằng Quang
   https://www.youtube.com/watch?v=D35dsUB9r2Y
** Sầu Trong Lòng Anh - Lương Bằng Quang (Album Return)
   https://www.youtube.com/watch?v=sDql-yNKmJ4
** Maroon 5 - Never Gonna Leave This Bed
   https://www.youtube.com/watch?v=ADmCFmYLns4
** Modern Talking - You're My Heart, You're My Soul (Video)
https://www.youtube.com/watch?v=4kHl4FoK1Ys
** No Face, No Name, No Number | Modern Talking | Lyrics [Kara + Vietsub HD]
   https://www.youtube.com/watch?v=lTFmLpRJkII
** Alexandra Stan - Lemonade (OFFICIAL MUSIC VIDEO)
   https://www.youtube.com/watch?v=4eWfRjyp2N
** BETWEEN THE RAINDROPS / LIFEHOUSE FT. NATASHA BEDINGFIELD / vietsub 木婉清
   https://www.youtube.com/watch?v=KbPigceQhbI
** Train - 50 Ways to Say Goodbye (Video)
   https://www.youtube.com/watch?v=GSBFehvLJDc
** Ellie Goulding - Starry Eyed
   https://www.youtube.com/watch?v=fBf2v4mLM8k
** Ellie Goulding - Burn
   https://www.youtube.com/watch?v=CGyEd0aKWZE
** Bruno Mars - Grenade [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=SR6iYWJxHqs
** Foster The People - Pumped up Kicks
   https://www.youtube.com/watch?v=SDTZ7iX4vTQ
** Lady Gaga - Poker Face
   https://www.youtube.com/watch?v=lcioXWfioa4
** Lady Gaga - Bad Romance
   https://www.youtube.com/watch?v=qrO4YZeyl0I
** Lady Gaga - Telephone ft. Beyoncé
   https://www.youtube.com/watch?v=GQ95z6ywcBY
** MØ - Final Song (Official Video)
   https://www.youtube.com/watch?v=WUcXQ--yGWQ
** Coldplay - Adventure Of A Lifetime (Official Video)
   https://www.youtube.com/watch?v=QtXby3twMmI
** Crazy Loop (Mm ma ma)
   https://www.youtube.com/watch?v=8qTFqnDpuvE
** Smallville and Remy Zero - Save Me
   https://www.youtube.com/watch?v=greTJhHhiHk
** Chris Brown - Next To You ft. Justin Bieber
   https://www.youtube.com/watch?v=EEuQU6a90Pc
** Katy Perry - Roar (Official)
   https://www.youtube.com/watch?v=CevxZvSJLk8
** Katy Perry - Part Of Me (Official)
   https://www.youtube.com/watch?v=uuwfgXD8qV8
** Katy Perry - The One That Got Away (Official)
   https://www.youtube.com/watch?v=Ahha3Cqe_fk
** Ed Sheeran - Give Me Love [Official Video]
   https://www.youtube.com/watch?v=FOjdXSrtUxA
** Skylar Grey - Words Lyrics
   https://www.youtube.com/watch?v=tcLJP3evnHI
** Skylar Grey - Coming Home (A.N.O. Remix)
   https://www.youtube.com/watch?v=NJIjvOdhx9o
** Aaron Smith - Dancin (KRONO Remix)
   https://www.youtube.com/watch?v=0XFudmaObLI
** "Beauty And A Beat" - Justin Bieber (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover)
   https://www.youtube.com/watch?v=9wqpfFI3EVE
** BIGBANG & 2NE1 - LOLLIPOP M/V
   https://www.youtube.com/watch?v=zIRW_elc-rY
** I Miss You - Mr. Siro (Lyrics Video)
   https://www.youtube.com/watch?v=fywHofbKinA
** Taylor Swift - Red
   https://www.youtube.com/watch?v=Zlot0i3Zykw
** Vanessa Carlton - A Thousand Miles
   https://www.youtube.com/watch?v=Cwkej79U3ek
** Imagine Dragons - It's Time
   https://www.youtube.com/watch?v=sENM2wA_FTg
** Tinie Tempah - Written In The Stars ft. Eric Turner
   https://www.youtube.com/watch?v=YgFyi74DVjc
** Kelly Clarkson - Because Of You (VIDEO)
   https://www.youtube.com/watch?v=Ra-Om7UMSJc
** Matt Cardle, Melanie C - Loving You
   https://www.youtube.com/watch?v=j3sRdbaMwgk
** Đôi Mắt - Wanbi Tuấn Anh [Official]
   https://www.youtube.com/watch?v=wzdCgedEAZQ
** Như một thói quen - tâm tít.MP4
   https://www.youtube.com/watch?v=_yMmpjcbQsc
** Lemon Tree - Fools Garden
   https://www.youtube.com/watch?v=Va0vs1fhhNI
** James Blunt - Wisemen [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=cueB7j4ZGrM
** James Blunt - You're Beautiful (Video)
   https://www.youtube.com/watch?v=oofSnsGkops
** James Blunt 1973 Official Video
   https://www.youtube.com/watch?v=11UQcLrzrN4
** LALALA - Soobin Hoàng Sơn - Official Music Video 4K
   https://www.youtube.com/watch?v=Ia_ddlGr1ic
** DAYDREAMS | Soobin Hoàng Sơn ft. BigDaddy | Nhạc trẻ hay tuyển chọn
   https://www.youtube.com/watch?v=o0GYK5Whk80
** Seafret - Oceans
   https://www.youtube.com/watch?v=aqsL0QQaSP4
** Seafret - Give Me Something
   https://www.youtube.com/watch?v=NhK4kGdio6E
** Nhac Phim - Ngoi Nha Hanh Phuc Han Quoc.flv
   https://www.youtube.com/watch?v=LbJdIdo6BEI
** Alizée - La Isla Bonita
   https://www.youtube.com/watch?v=xq-aTe77bkA
** 1. Blue Swede - Hooked on a Feelingj
   https://www.youtube.com/watch?v=NrI-UBIB8Jk
** Aimer - Kataomoi
   https://www.youtube.com/watch?v=zSOJk7ggJts
** Enrique Iglesias - I'm A Freak ft. Pitbull
   https://www.youtube.com/watch?v=YUiVIPgJA0o
** Fuck You - Lily Allen (Lyrics)
   https://www.youtube.com/watch?v=OK4fJhbRL1g
** TOULIVER X LÊ HIẾU X SOOBIN HOÀNG SƠN - NGÀY MAI EM ĐI 2017 | OFFICIAL LYRIC VIDEO
   https://www.youtube.com/watch?v=z5Jc7KiTLbs
** Jason Mraz & Colbie Caillat - Lucky [Official Video]
   https://www.youtube.com/watch?v=acvIVA9-FMQ
** Of Monsters And Men - Dirty Paws (Official Lyric Video)
   https://www.youtube.com/watch?v=mCHUw7ACS8o
** Of Monsters And Men - Little Talks (Official Video)
   https://www.youtube.com/watch?v=ghb6eDopW8I
** [MV] 케이윌(K.will) - 이러지마 제발 (Please don't...)
   https://www.youtube.com/watch?v=PdUiCJnRptk
** Adele - When We Were Young (Live at The Church Studios)
   https://www.youtube.com/watch?v=DDWKuo3gXMQ
** Coldplay - All I Can Think About Is You (Official Lyric Video)
   https://www.youtube.com/watch?v=KnLNG0WnGsI
** Fun.: Some Nights [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=qQkBeOisNM0
** 2NE1 - LONELY M/V
   https://www.youtube.com/watch?v=5n4V3lGEyG4
** OneRepublic - All The Right Moves
   https://www.youtube.com/watch?v=qrOeGCJdZe4
** OneRepublic - If I Lose Myself
   https://www.youtube.com/watch?v=TGx0rApSk6w
** Timbaland - Apologize ft. OneRepublic
   https://www.youtube.com/watch?v=ZSM3w1v-A_Y
** Ed Sheeran - Lego House [Official Video]
   https://www.youtube.com/watch?v=c4BLVznuWnU
** Fun.: Carry On [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=q7yCLn-O-Y0
** Michael Jackson - Billie Jean (Official Video)
   https://www.youtube.com/watch?v=Zi_XLOBDo_Y
** Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers
   https://www.youtube.com/watch?v=5NV6Rdv1a3I
** Kelly Clarkson - Dark Side
   https://www.youtube.com/watch?v=H5ArpRWcGe0
* 5
** Mãi Mãi Là Của Nhau | Bùi Anh Tuấn | Official MV
https://www.youtube.com/watch?v=S-eVMDDeDag
** [Lyrics+Vietsub] Clean Bandit - Rockabye (ft. Sean Paul & Anne-Marie)
https://www.youtube.com/watch?v=wIeNQfbNwxI
** Clean Bandit - Rather Be ft. Jess Glynne [Official Video]
https://www.youtube.com/watch?v=m-M1AtrxztU
** Galantis - Runaway (U & I) (Official Video)
https://www.youtube.com/watch?v=5XR7naZ_zZA&list=PLxXfKNWPJO6VMAyElTR0vQ5_ctSbPd5mh
** [Vietsub] DBSK - Why Did I Fall In Love With You
https://www.youtube.com/watch?v=v9cfJfQm9RU
** P!nk - Try
   https://www.youtube.com/watch?v=yTCDVfMz15M
** Khuôn Mặt Đáng Thương - Sơn Tùng M-TP
   https://www.youtube.com/watch?v=HHmidNM2sOM
** Snow Patrol - Life On Earth
   https://www.youtube.com/watch?v=XqYWcp1JH7Y
** Kelly Clarkson - Catch My Breath
   https://www.youtube.com/watch?v=HEValZuFYRU
** Cash Cash - How To Love ft Sofia Reyes (Official Video)
   https://www.youtube.com/watch?v=peByeoQhjMM
** OneRepublic - Something I Need
   https://www.youtube.com/watch?v=qKCGBgOgp08
** OneRepublic - I Lived
   https://www.youtube.com/watch?v=z0rxydSolwU
** Maroon 5 - Misery
   https://www.youtube.com/watch?v=6g6g2mvItp4
** Maroon 5 - Love Somebody
   https://www.youtube.com/watch?v=MU8B4XDI3Uw
** [Vietsub + Kara Pinyin] Vén rèm châu - Hoắc Tôn
   https://www.youtube.com/watch?v=_ksbijvvTCI
** [vietsub] LẠNH LẼO - 涼涼 (OST Tam Sinh Tam Thế Thập Lý Đào Hoa)
   https://www.youtube.com/watch?v=V8PZEGGv9qo
** Space Oddity
   https://www.youtube.com/watch?v=KaOC9danxNo
** Eagles - Hotel California (Lyrics)
   https://www.youtube.com/watch?v=EqPtz5qN7HM
** Rihanna - Diamonds
   https://www.youtube.com/watch?v=lWA2pjMjpBs
** Jaymes Young - I'll Be Good [Official Video]
   https://www.youtube.com/watch?v=scd-uNNxgrU
** Carly Rae Jepsen - I Really Like You
   https://www.youtube.com/watch?v=qV5lzRHrGeg
** Felix Jaehn - Ain’t Nobody (Loves Me Better) ft. Jasmine Thompson
   https://www.youtube.com/watch?v=5j1RCys4R0g
** Kygo - Firestone (Official Video) ft. Conrad Sewell
   https://www.youtube.com/watch?v=9Sc-ir2UwGU
** Kygo - Raging ft. Kodaline
   https://www.youtube.com/watch?v=ZhzN7-Q00KU
** Jonas Blue - Fast Car ft. Dakota
   https://www.youtube.com/watch?v=5yXQJBU8A28
** Taylor Swift - Wildest Dreams
   https://www.youtube.com/watch?v=IdneKLhsWOQ
** Taylor Swift - Everything Has Changed ft. Ed Sheeran
   https://www.youtube.com/watch?v=w1oM3kQpXRo
** Taylor Swift - Style
   https://www.youtube.com/watch?v=-CmadmM5cOk
** P!nk - Just Give Me A Reason ft. Nate Ruess
   https://www.youtube.com/watch?v=OpQFFLBMEPI
** Christina Perri - The Lonely [Official Lyric Video]
   https://www.youtube.com/watch?v=HO4e4nCYBEo
** Christina Perri - Tragedy [Official Lyric Video]
   https://www.youtube.com/watch?v=nNsZVO6Yy0k
** Tình Yêu Màu Nắng - Đạo Diễn Triệu Quang Huy - Đoàn Thúy Trang ft. Big Daddy - (Ninja Official MV)
   https://www.youtube.com/watch?v=D-6JDufCJ1Y
** Đen - Trời ơi con chưa muốn chết (Prod. by Tantu Beats)
   https://www.youtube.com/watch?v=ArexdEMWRlA
** Ta và Nàng - Đen ft. JGKiD (Lyric Video / TAS Release)
   https://www.youtube.com/watch?v=rPU41Mw7txo
** Charlie Puth - One Call Away [Official Video]
   https://www.youtube.com/watch?v=BxuY9FET9Y4
** Zedd - Stay The Night ft. Hayley Williams
   https://www.youtube.com/watch?v=i-gyZ35074k
** OneRepublic - Love Runs Out
   https://www.youtube.com/watch?v=0OWj0CiM8WU
** Imagine Dragons - Next To Me (Audio)
   https://www.youtube.com/watch?v=-C_rvt0SwLE
** CƠN MƯA CUỐI - Binz ft. JustaTee ( OFFICIAL )
   https://www.youtube.com/watch?v=1yVqSSDRu78
** [Official MV] Crying Over You - JustaTee ft. Binz
   https://www.youtube.com/watch?v=tcat9CPiAZ4
** Rudimental - Waiting All Night ft. Ella Eyre [Official Video]
   https://www.youtube.com/watch?v=M97vR2V4vTs
** Avicii - The Nights
   https://www.youtube.com/watch?v=UtF6Jej8yb4
** Fun.: We Are Young ft. Janelle Monáe [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=Sv6dMFF_yts
** Maroon 5 - Payphone (Explicit) ft. Wiz Khalifa
   https://www.youtube.com/watch?v=KRaWnd3LJfs
** Snow Patrol - The Sunlight Through the Flags (Part 2 of The Lightning Strike)
   https://www.youtube.com/watch?v=cHl6dLaUAjk
** Jang Nara Sweet Dream MV
   https://www.youtube.com/watch?v=ITJlByULnhY
** Lost Frequencies feat. Janieck Devy - Reality (Official Music Video)
   https://www.youtube.com/watch?v=ilw-qmqZ5zY
** Alan Walker - The Spectre
   https://www.youtube.com/watch?v=wJnBTPUQS5A
** Tez Cadey - Seve
   https://www.youtube.com/watch?v=t5747BhezKM
** Selena Gomez - Bad Liar
   https://www.youtube.com/watch?v=NZKXkD6EgBk
** Stoto - Still Can't Sleep (Original Mix)
   https://www.youtube.com/watch?v=UAHaxlCe29E
** Vitas - Opera N2
   https://www.youtube.com/watch?v=tITWIcNeTjw
** Of Monsters and Men - King And Lionheart (Official Video)
   https://www.youtube.com/watch?v=A76a_LNIYwE
** [Vietsub | Hán Việt] Đồng Thoại - Quang Lương (Music Gift For You No.2)
   https://www.youtube.com/watch?v=DjOEbfGyANA
** Sứ thanh hoa 青花瓷 - Jay Chou
   https://www.youtube.com/watch?v=CZ78y__MIzM
** [Vietsub][HD] Endless Love (The Myth Theme Song) - Jackie Chan & Kim Hee Sun
   https://www.youtube.com/watch?v=EwuyNZDojg8
* 6
** BIGBANG - TELL ME GOODBYE M/V
https://www.youtube.com/watch?v=GE_4RtpVVaw
** Drake - Take Care ft. Rihanna
https://www.youtube.com/watch?v=-zzP29emgpg
** Gym Class Heroes: The Fighter ft. Ryan Tedder [OFFICIAL VIDEO]
https://www.youtube.com/watch?v=bxV-OOIamyk
** Mr. Probz - Space For Two
   https://www.youtube.com/watch?v=gsGn1dzITD0
** The Catalyst (Official Video) - Linkin Park
   https://www.youtube.com/watch?v=51iquRYKPbs
** Ellie Goulding - Beating Heart
   https://www.youtube.com/watch?v=wrNTOo4KH8c
** One Direction - You & I
   https://www.youtube.com/watch?v=_kqQDCxRCzM
** R. City - Locked Away ft. Adam Levine
   https://www.youtube.com/watch?v=6GUm5g8SG4o
** Katy Perry - California Gurls (Official) ft. Snoop Dogg
   https://www.youtube.com/watch?v=F57P9C4SAW4
** Maroon 5 - Maps (Lyric Video)
   https://www.youtube.com/watch?v=Y7ix6RITXM0
** Avicii - For A Better Day
   https://www.youtube.com/watch?v=Xq-knHXSKYY
** Shakira - Loca (Spanish Version) ft. El Cata
   https://www.youtube.com/watch?v=XAhTt60W7qo
** Loka Loka Loka toka toka toka
   https://www.youtube.com/watch?v=SbBeAlCtciw
** Blackbear - IDFC (Acoustic Version)
   https://www.youtube.com/watch?v=NR7-n-D2HhA
** Lilly Wood & The Prick - Prayer in C (Robin Schulz remix) [Clip officiel]
   https://www.youtube.com/watch?v=JrlfFTS9kGU
** The Chainsmokers - Roses (Official Video) ft. ROZES
   https://www.youtube.com/watch?v=G5Mv2iV0wkU
** Enrique Iglesias - Heart Attack
   https://www.youtube.com/watch?v=sC2nElyx7Ds
** Imagine Dragons - Shots
   https://www.youtube.com/watch?v=qQrgto184Tk
** Mike Posner - I Took A Pill In Ibiza (Seeb Remix) (Explicit)
   https://www.youtube.com/watch?v=foE1mO2yM04
** Jaymes Young - Habits of My Heart (Official Audio)
   https://www.youtube.com/watch?v=CDJOP16yNdY
** Tangled - I See The Light - Mandy Moore
   https://www.youtube.com/watch?v=RyrYgCvxBUg 
** Dua Lipa - New Rules (Official Music Video)
   https://www.youtube.com/watch?v=k2qgadSvNyU
** Camila Cabello - Havana ft. Young Thug
   https://www.youtube.com/watch?v=BQ0mxQXmLsk
** Charlie Puth - Attention [Official Video]
   https://www.youtube.com/watch?v=nfs8NYg7yQM
** Christina Perri ft. Jason Mraz - Distance [Official Music Video]
   https://www.youtube.com/watch?v=ROqTa1mn_qc
** Girls' Generation 소녀시대 'Gee' MV
   https://www.youtube.com/watch?v=U7mPqycQ0tQ
** TWICE "LIKEY" M/V
   https://www.youtube.com/watch?v=V2hlQkVJZhE
** Mãi Mãi Là Của Nhau | Bùi Anh Tuấn | Official MV
   https://www.youtube.com/watch?v=S-eVMDDeDag
** FBBOIZ - Để Em Rời Xa ( Music Video Official)
   https://www.youtube.com/watch?v=KUtaJeL_FzE
** [OFFICIAL MV] Thu Cuối - Mr.T ft Yanbi & Hằng Bingboong
   https://www.youtube.com/watch?v=QETfX44-PB8
** B.o.B - Both of Us ft. Taylor Swift [Official Video]
   https://www.youtube.com/watch?v=1sa9qeV6T0o
** The Chainsmokers - Paris (Video)
   https://www.youtube.com/watch?v=fRNkQH4DVg8
** Imagine Dragons - Radioactive
   https://www.youtube.com/watch?v=ktvTqknDobU
** 7. Jackson 5 - I Want You Back
   https://www.youtube.com/watch?v=DGDyAb6pePo
** Lucky Twice- Lucky (I'm so lucky lucky!) with lyrics on screen
   https://www.youtube.com/watch?v=MBtLD7IbsEA
** Mc Mong ft . Mellow - Sick Enough To Die
   https://www.youtube.com/watch?v=fwS74MG5JMg
** T-ara & Supernova(티아라 & 초신성) _ TTL (TIME TO LOVE) MV
   https://www.youtube.com/watch?v=NFFgRRLInD4
** Merk & Kremont - Sad Story (Out Of Luck) [Official Music Video]
   https://www.youtube.com/watch?v=8GotXeCwUnc
** P!nk - Blow Me (One Last Kiss)
   https://www.youtube.com/watch?v=3jNlIGDRkvQ
** Halsey - Colors
   https://www.youtube.com/watch?v=JGulAZnnTKA
** Mirrors - Justin Timberlake
*** (Boyce Avenue feat. Fifth Harmony cover) on Apple & Spotify
    https://www.youtube.com/watch?v=fvEZUbzqqyM
*** Justin Timberlake - Mirrors
    https://www.youtube.com/watch?v=uuZE_IRwLNI
** Vietsub | Hán Việt] Song Phi - Hà Nhuận Đông (Ost Lương Sơn Bá Chúc Anh Đài 2007)
   https://www.youtube.com/watch?v=Vaclu3ZmHlQ
** [MV Full HD] Those Years - Hu Xia [Vietsub + Kara FX] (You Are the Apple of My Eye's OST)
   https://www.youtube.com/watch?v=UBehxEC8c-4
** Of Monsters And Men - Love Love Love (Official Lyric Video)
   https://www.youtube.com/watch?v=beiPP_MGz6I
** Gotye - Somebody That I Used To Know (feat. Kimbra) - official video
   https://www.youtube.com/watch?v=8UVNT4wvIGY
** B.o.B - Airplanes ft. Hayley Williams
   https://www.youtube.com/watch?v=eVcvBmFF_lU
** Avicii - Wake Me Up (Official Video)
   https://www.youtube.com/watch?v=IcrbM1l_BoI
** Safe & Sound feat. The Civil Wars (The Hunger Games: Songs From District 12 And Beyond)
   https://www.youtube.com/watch?v=RzhAS_GnJIc
* 7
** TGC - Dreamers (Embody Remix) [Official Video]
   https://www.youtube.com/watch?v=hrhGU1I1d8s
** 【抖音神曲】Pascal Letoublon - Friendships (Original Mix) 高音質 / 動態純樂版MV
https://www.youtube.com/watch?v=dINnW3NJA4Q
** Nếu ‣ Onionn. x marzuz ᴸʸʳᶦᶜ ᵛᶦᵈᵉᵒ
https://www.youtube.com/watch?v=_kSR8XP_zbw
** Jessie J - Domino
   https://www.youtube.com/watch?v=UJtB55MaoD0
** Nelly - Dilemma ft. Kelly Rowland
   https://www.youtube.com/watch?v=8WYHDfJDPDc
** Britney Spears - Criminal
   https://www.youtube.com/watch?v=s6b33PTbGxk
** The Killers - When You Were Young
   https://www.youtube.com/watch?v=ff0oWESdmH0
** Ke$ha - Die Young (Official)
   https://www.youtube.com/watch?v=NOubzHCUt48
** M83 'Midnight City' Official video
   https://www.youtube.com/watch?v=dX3k_QDnzHE
** David Guetta - She Wolf (Falling To Pieces) ft. Sia (Official Video)
   https://www.youtube.com/watch?v=PVzljDmoPVs
** Martin Solveig & GTA - Intoxicated (Official Music Video)
   https://www.youtube.com/watch?v=94Rq2TX0wj4
** Koven & Crystal Skies - You Me And Gravity 
   https://www.youtube.com/watch?v=QkWRN6MHTlM
** Kisnou - Ilia 
   https://www.youtube.com/watch?v=tLwGwOsESB4
** Armin van Buuren - In And Out Of Love (The Blizzard Remix) [Music Video] [HD]
https://www.youtube.com/watch?v=XSLkGIdswCY
** [FMV Vietsub] Là Tự Em Đa Tình 多情种 // Vũ Văn Nguyệt x Sở Kiều // Sở Kiều truyện 楚乔传 【星玥】
   https://www.youtube.com/watch?v=56pFvLoRuLY
** Mr. Probz - Waves (Robin Schulz Remix Radio Edit)
   https://www.youtube.com/watch?v=pUjE9H8QlA4
** Duke Dumont - I Got U (Official video) ft. Jax Jones
   https://www.youtube.com/watch?v=FHCYHldJi_g
** Lilly Wood & The Prick and Robin Schulz - Prayer In C (Robin Schulz Remix) (Official)
   https://www.youtube.com/watch?v=fiore9Z5iUg
** Spirit - Here I Am(HD)
   https://www.youtube.com/watch?v=2MSwZBF95Kc
** Arc North - Meant To Be (ft .Krista Marina)
   https://www.youtube.com/watch?v=x_o1bZnXZgQ
** The Fray - How to Save a Life (New Video Version)
   https://www.youtube.com/watch?v=cjVQ36NhbMk
** Lukas Graham - 7 Years [OFFICIAL LYRIC VIDEO]
   https://www.youtube.com/watch?v=jErJimwom94
** Christina Perri - Human [Official Video]
   https://www.youtube.com/watch?v=r5yaoMjaAmE
** Taeyang - Wedding Dress [HD]
   https://www.youtube.com/watch?v=Sjcvasr-6o0
** Đừng Ngoảnh Lại - Lưu Hương Giang ft. Suboi ft Cường Seven [Official]
   https://www.youtube.com/watch?v=go1njpQr_m4
** TOULIVER X BINZ - THEY SAID [ OFFICIAL MV ]
   https://www.youtube.com/watch?v=XdBsAXOxYfo
** The Kooks - Bad Habit
   https://www.youtube.com/watch?v=3tUh-x-fp8Q
** Ngẫu Hứng Hoaprox
   https://www.youtube.com/watch?v=vtskUyVJYVA
** [Official Video]5PM-Liêu Anh Tuấn.mp4
   https://www.youtube.com/watch?v=HBVBc5LHxRk
** Foster The People - Pumped up Kicks
   https://www.youtube.com/watch?v=SDTZ7iX4vTQ
** Zara Larsson - Lush Life
   https://www.youtube.com/watch?v=tD4HCZe-tew
** The Killers - Just Another Girl
   https://www.youtube.com/watch?v=3BwzP1laWkQ
** The Killers - Human
   https://www.youtube.com/watch?v=RIZdjT1472Y
** [Vietsub+Kara] 5cm/s AMV - Sakura anata ni deaete yokatta
   https://www.youtube.com/watch?v=WAT-Gy6QsTY
** Adele - Set Fire To The Rain (Live at The Royal Albert Hall)
   https://www.youtube.com/watch?v=Ri7-vnrJD3k
** Adele - Rolling in the Deep
   https://www.youtube.com/watch?v=rYEDA3JcQqw
** [Vietsub | Hán Việt] Kiếm Hồn - Lý Vĩ (Ost Tân Anh Hùng Xạ Điêu 2017)
   https://www.youtube.com/watch?v=4MOsX9sE1VA
** Descendants Of The Sun-[HD] OST||Once Again- Kim Na-Young ft Mad Clown
   https://www.youtube.com/watch?v=PKIU4ebQxOA
** TAEYANG - 눈,코,입 (EYES, NOSE, LIPS) M/V
   https://www.youtube.com/watch?v=UwuAPyOImoI
** Tinh Ve Noi Dau-Where Do We Go (Thanh Bui ft. Tata Young)
   https://www.youtube.com/watch?v=wEBgnZl9L0o
* 8
** Vô Hình Trong Tim Em - Mr. Siro [Video Lyric HD]
   https://www.youtube.com/watch?v=UrBa0cm97cc
** Beatrich - Superstar
   https://www.youtube.com/watch?v=Ju0YMKNW6X0
** [Vietsub + Hangul + Kara] Vua Xe Đụng (Bumper King) OST (2004 SBS 범퍼킹 OST)
   https://www.youtube.com/watch?v=PegeZL1GR0o
** [Kara - Vietsub]A world without danger - OST Code Lyoko (MV Code Lyoko Evolution)
   https://www.youtube.com/watch?v=oewuMxWvGZ4&t=24s
** will.i.am - Scream & Shout ft. Britney Spears
   https://www.youtube.com/watch?v=kYtGl1dX5qI
** Zara Larsson, MNEK - Never Forget You
   https://www.youtube.com/watch?v=GTyN-DB_v5M
** Avicii - You Make Me (Official)
   https://www.youtube.com/watch?v=2GADx4Hy-Gg
** Years & Years - Take Shelter
   https://www.youtube.com/watch?v=Z0atZQSUE80
** Of Monsters And Men - Yellow Light (Official Lyric Video)
   https://www.youtube.com/watch?v=aBlKPLeLU_s
** Mark Forster - Wir sind groß
   https://www.youtube.com/watch?v=Djnzvff7A4Q
** Max Giesinger - 80 Millionen
   https://www.youtube.com/watch?v=MP8DRaj730Y
** Aerosmith - I Don't Want to Miss a Thing (Video)
   https://www.youtube.com/watch?v=JkK8g6FMEXE
** Alan Walker - Sing Me To Sleep
   https://www.youtube.com/watch?v=2i2khp_npdE
** Alan Walker - Faded
   https://www.youtube.com/watch?v=60ItHLz5WEA
** All Izz Well [Full HD Song] 3 Idiots
   https://www.youtube.com/watch?v=S-LltgOtFSg
** GIẤC MƠ CHỈ LÀ GIẤC MƠ HỒ NGỌC HÀ
   https://www.youtube.com/watch?v=F8_S2E9gJ7s
** Đã Từng - Bùi Anh Tuấn Ft. Dương Hoàng Yến [Video Lyric HD]
   https://www.youtube.com/watch?v=VjJd5Ln_bmQ
** The Chainsmokers - Closer (Lyric) ft. Halsey
   https://www.youtube.com/watch?v=PT2_F-1esPk
** BEAST - 'FICTION' (Official Music Video)
   https://www.youtube.com/watch?v=ZAzWT8mRoR0
** Evanescence - Bring Me To Life
   https://www.youtube.com/watch?v=3YxaaGgTQYM
** Britney Spears - ...Baby One More Time
   https://www.youtube.com/watch?v=C-u5WLJ9Yk4
** David Guetta & Showtek - Bad ft.Vassy (Lyrics Video)
   https://www.youtube.com/watch?v=oC-GflRB0y4
** Calvin Harris - Blame ft. John Newman
   https://www.youtube.com/watch?v=6ACl8s_tBzE
** Calvin Harris - Summer
   https://www.youtube.com/watch?v=ebXbLfLACGM
** Swedish House Mafia - Don't You Worry Child ft. John Martin
   https://www.youtube.com/watch?v=1y6smkh6c-0
   https://www.youtube.com/watch?v=N1kpeRhqVzI mix
** Far East Movement - Like A G6 ft. The Cataracs, DEV
   https://www.youtube.com/watch?v=w4s6H4ku6ZY
** The Killers - Miss Atomic Bomb
   https://www.youtube.com/watch?v=Qok9Ialei4c
** Snow Patrol - The Lightning Strike (What If This Storm Ends?)
   https://www.youtube.com/watch?v=S0BDS0-ZwOw
** will.i.am - #thatPOWER ft. Justin Bieber
   https://www.youtube.com/watch?v=DGIgXP9SvB8
** Austin Mahone - Mmm Yeah ft. Pitbull
   https://www.youtube.com/watch?v=MMAppa1cAVo
** CloZee - Secret Place
   https://www.youtube.com/watch?v=soLrXM0EQ8c
** Bệnh Của Anh - Khói [Lyric Video]
   https://www.youtube.com/watch?v=FFwasFKSjSg
** Call Me - Koo [Lyric Video] ( Prod. Danny EB )
   https://www.youtube.com/watch?v=FWkW-YkzCJ4
** [Full MV] 2PM & SNSD - Caribbean Bay CABI Song
   https://www.youtube.com/watch?v=EiheWWaWApc
** DARA - KISS M/V
   https://www.youtube.com/watch?v=ZAqiMCp9zrI
** Imagine Dragons - Whatever It Takes
   https://www.youtube.com/watch?v=gOsM-DYAEhY
** Maroon 5 - Wait
   https://www.youtube.com/watch?v=4uTNVumfm84
** G-DRAGON - HEARTBREAKER M/V
   https://www.youtube.com/watch?v=LOXEVd-Z7NE
** BIGBANG - LIES(거짓말) M/V
   https://www.youtube.com/watch?v=2Cv3phvP8Ro
** GD X TAEYANG - GOOD BOY M/V
   https://www.youtube.com/watch?v=1ZRb1we80kM
** Justin Timberlake - Suit & Tie (Official) ft. JAY Z
   https://www.youtube.com/watch?v=IsUsVbTj2AY
** Moby - Lift Me Up
   https://www.youtube.com/watch?v=CWGNA3u4-Sg
** Avril Lavigne - When You're Gone (Official Video)
   https://www.youtube.com/watch?v=0G3_kG5FFfQ
** The Chainsmokers - #SELFIE
   https://www.youtube.com/watch?v=ZuwfZGDWOio
* 9
** Zedd, Alessia Cara - Stay (Lyric Video)
https://www.youtube.com/watch?v=h--P8HzYZ74
** Route 94 - My Love (Official Video) ft. Jess Glynne
https://www.youtube.com/watch?v=BS46C2z5lVE
** Lana Del Rey - Blue Jeans
   https://www.youtube.com/watch?v=JRWox-i6aAk
** Lana Del Rey - Born To Die
   https://www.youtube.com/watch?v=Bag1gUxuU0g
** Gesaffelstein - Viol
   https://www.youtube.com/watch?v=CIpyBeBpC74
** Axel Johansson - The River (Official Video)
   https://www.youtube.com/watch?v=6Ai0XF9isk4
** Ship Wrek - Pain (feat. Mia Vaile) [NCS Release]
   https://www.youtube.com/watch?v=UDEpRK8WL_I
** BIGBANG - Fantastic Baby MV [YG Entertainment - Trinity Optima Production]
   https://www.youtube.com/watch?v=D2H1_hmutTo
** Avril Lavigne - Let Me Go ft. Chad Kroeger
   https://www.youtube.com/watch?v=AqajUg85Ax4
** Bon Jovi - It's My Life
   https://www.youtube.com/watch?v=vx2u5uUu3D E
** Unknown Brain - Superhero (feat. Chris Linton) [NCS Release]
   https://www.youtube.com/watch?v=LHvYrn3FAgI
** The Orb - Little Fluffy Clouds
   https://www.youtube.com/watch?v=FHixChYgGRI
** Avicii - Waiting For Love
   https://www.youtube.com/watch?v=cHHLHGNpCSA
** DVBBS & Borgeous - TSUNAMI (Original Mix)
   https://www.youtube.com/watch?v=0EWbonj7f18
** Khu Tao Song -Wowy+Karik (OFFICIAL VIDEO HD) ©SouthGanz 2010
   https://www.youtube.com/watch?v=UZ2M12BeKX4
** Lorde - Royals (US Version)
   https://www.youtube.com/watch?v=nlcIKh6sBtc
** MACKLEMORE & RYAN LEWIS - CAN'T HOLD US FEAT. RAY DALTON (OFFICIAL MUSIC VIDEO)
   https://www.youtube.com/watch?v=2zNSgSzhBfM
** Lemaitre - Higher ft. Maty Noyes
   https://www.youtube.com/watch?v=bsENfTmAdeI
** Skrillex & Damian "Jr. Gong" Marley - Make It Bun Dem [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=BGpzGu9Yp6Y
** CAZZETTE - She Wants Me Dead (CAZZETTE vs. AronChupa) [Official Video] ft. The High
   https://www.youtube.com/watch?v=FHccClTAdzc
** twenty one pilots: Stressed Out [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=pXRviuL6vMY
** Nelly - Just A Dream
   https://www.youtube.com/watch?v=N6O2ncUKvlg
** Eminem - Rap God (Explicit)
   https://www.youtube.com/watch?v=XbGs_qK2PQA
** Logan | Way Down We Go | Music Video
   https://www.youtube.com/watch?v=LCkyW7RE6Wk
** Cùng Anh - Ngọc Dolil (VRT Mix)
   https://www.youtube.com/watch?v=V9S5QPbzPoo
** Caravan Palace - Lone Digger
   https://www.youtube.com/watch?v=UbQgXeY_zi4
** Hai Thế Giới full - Wowy & Karik ( Offical Video HD full ) ©SouthGanz Entertainment
   https://www.youtube.com/watch?v=3JLDUJJuVGk
** DEV - Bass Down Low (Explicit) ft. The Cataracs
   https://www.youtube.com/watch?v=OOAMfUJ3tsc
** Imagine Dragons - Thunder
   https://www.youtube.com/watch?v=fKopy74weus
** Eminem - Love The Way You Lie ft. Rihanna
   https://www.youtube.com/watch?v=uelHwf8o7_U
* 10
** Black Sabbath ~ War Pigs
   https://www.youtube.com/watch?v=LQUXuQ6Zd9w
** Selena Gomez - Kill Em With Kindness
   https://www.youtube.com/watch?v=HHP5MKgK0o8
** Gesaffelstein OMEGA (2015)
   https://www.youtube.com/watch?v=hFvBb7aarbs
** Lorde - Hard Feelings
   https://www.youtube.com/watch?v=d6nYF3juDQY
** Mogwai - Take Me Somewhere Nice
   https://www.youtube.com/watch?v=luM6oeCM7Yw
** Cartoon - Why We Lose (feat. Coleman Trapp) [NCS Release]
   Cartoon - Why We Lose (feat. Coleman Trapp) [NCS Release]
** Cartoon - On & On (feat. Daniel Levi) [NCS Release]
   https://www.youtube.com/watch?v=K4DyBUG242c
** Legends Never Die (ft. Against The Current) | Worlds 2017 - League of Legends
   https://www.youtube.com/watch?v=r6zIGXun57U
** Arctic Monkeys - Do I Wanna Know? (Official Video)
   https://www.youtube.com/watch?v=bpOSxM0rNPM
** Imagine Dragons - Believer
   https://www.youtube.com/watch?v=7wtfhZwyrcc
** Drive "A Real Hero" Movie Tribute
   https://www.youtube.com/watch?v=MJvCI9NT9M8
** Kavinsky - Nightcall "Drive"
   https://www.youtube.com/watch?v=30jrmzzgHLc
** Martin Garrix - Animals (Official Video)
   https://www.youtube.com/watch?v=gCYcHz2k5x0
** Calvin Harris & Alesso - Under Control ft. Hurts
   https://www.youtube.com/watch?v=yZqmarGShxg
** DJ Tiesto - Welcome To Ibiza
   https://www.youtube.com/watch?v=-JOlwVia1As
** Eminem - Lose Yourself [HD]
   https://www.youtube.com/watch?v=_Yhyp-_hX2s
** Dimitri Vegas, Martin Garrix, Like Mike - Tremor (Official Music Video)
   https://www.youtube.com/watch?v=9vMh9f41pqE
** Requiem For A Dream Full Song HD
   https://www.youtube.com/watch?v=yVIRcnlRKF8
** CAZZETTE - She Wants Me Dead (CAZZETTE vs. AronChupa) [Official Video] ft. The High
   https://www.youtube.com/watch?v=FHccClTAdzc
** The XX - Intro HQ
   https://www.youtube.com/watch?v=AZ1pHmWhIuY
** clubbed to death - Matrix soundtrack
   https://www.youtube.com/watch?v=XbxZargtXug
** In The End (Official Video) - Linkin Park
   https://www.youtube.com/watch?v=eVTXPUF4Oz4
** Numb (Official Video) - Linkin Park
   https://www.youtube.com/watch?v=kXYiU_JCYtU
** Skrillex & Damian "Jr. Gong" Marley - Make It Bun Dem [OFFICIAL VIDEO]
   https://www.youtube.com/watch?v=BGpzGu9Yp6Y
** Avicii - Levels
   https://www.youtube.com/watch?v=_ovdm2yX4MA
* Indie
** Kygo & Imagine Dragons - Born To Be Yours (Lyric Video)
https://www.youtube.com/watch?v=mOFvJVroAJE
** Martin Garrix feat. Khalid - Ocean (Official Video)
https://www.youtube.com/watch?v=BDocp-VpCwY
** M83 - Un Nouveau Soleil (audio)
   https://www.youtube.com/watch?v=36mlX318Q3w
** Jónsi - Gathering Stories (From We Bought A Zoo)
   https://www.youtube.com/watch?v=KyKK55SUqDk
** 8D
*** Chill, calm, relaxing and downtempo stuff or whatever
***  Vexento - Lonely Dance
https://www.youtube.com/watch?v=tvQvpIy9JnA&list=PLcd3emSF7UMCEVznCb2foDghKoq7ehcD1
